name: Build ESP32IGate

on:
  workflow_dispatch:  # 允许手动触发工作流
  push:
    branches: [ main ]  # 也可以配置为代码推送时自动触发

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          
      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio
          
      - name: Run PlatformIO Build
        run: platformio run -e esp32-sh1106
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            ./.pio/build/**/*.bin
            ./.pio/build/**/*.elf  
